======================================================================== test session starts =========================================================================
platform linux -- Python 3.10.10, pytest-8.1.1, pluggy-1.4.0
rootdir: /home/jupyter-misterdx/github/team22/users/avlotsmanov/exercise/hw5
plugins: anyio-4.2.0
collected 46 items

test_hw5_sets.py ..F...F...........F...........................                                                                                                [100%]

============================================================================== FAILURES ==============================================================================
________________________________________________________________________ test_set_union_neg_2 ________________________________________________________________________

    def test_set_union_neg_2():
        mas = [2,3]
        set1 = {14, 15, 16}
        try:
            set_union(mas, set1)
        except TypeError:
            assert True
        else:
>           assert False, "Функция не вызвала исключение TypeError"
E           AssertionError: Функция не вызвала исключение TypeError
E           assert False

test_hw5_sets.py:30: AssertionError
_____________________________________________________________________ test_set_difference_neg_1 ______________________________________________________________________

    def test_set_difference_neg_1():
        try:
            set_difference({1, 2}, {12, 2})
        except TypeError:
            assert True
        else:
>           assert False, "Функция не вызвала исключение TypeError"
E           AssertionError: Функция не вызвала исключение TypeError
E           assert False

test_hw5_sets.py:52: AssertionError
______________________________________________________________________ test_combine_sets_neg_2 _______________________________________________________________________

    def test_combine_sets_neg_2():
        try:
            combine_sets(
                {1, 2},
                [2, 3, 5],
                {2, 4, 8, 9}
            )
        except TypeError:
            assert True
        else:
>           assert False, "Функция не вызвала исключение TypeError"
E           AssertionError: Функция не вызвала исключение TypeError
E           assert False

test_hw5_sets.py:144: AssertionError
====================================================================== short test summary info =======================================================================
FAILED test_hw5_sets.py::test_set_union_neg_2 - AssertionError: Функция не вызвала исключение TypeError
FAILED test_hw5_sets.py::test_set_difference_neg_1 - AssertionError: Функция не вызвала исключение TypeError
FAILED test_hw5_sets.py::test_combine_sets_neg_2 - AssertionError: Функция не вызвала исключение TypeError
==================================================================== 3 failed, 43 passed in 0.08s ====================================================================
